--- 
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - ree
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
branches:
  only:
    - master
notifications: 
  recipients:
  - caizhaoff@gmail.com
before_script: 
- gem install hoe-travis --no-rdoc --no-ri
- rake travis:before -t
after_script: 
- rake travis:after -t
script: rake
